--Insertion of profileTable
--INSERT INTO profile_dropdown(profile_id,profile_source)
--VALUES (1,"Indeed");
--INSERT INTO profile_dropdown(profile_id,profile_source)
--VALUES (2,"LinkedIn");
--INSERT INTO profile_dropdown(profile_id,profile_source)
--VALUES (3,"Naukri");
--INSERT INTO profile_dropdown(profile_id,profile_source)
--VALUES (4,"Glassdoor");
--INSERT INTO profile_dropdown(profile_id,profile_source)
--VALUES (5,"Monster");
--INSERT INTO profile_dropdown(profile_id,profile_source)
--VALUES (6,"CareerBuilder");
--INSERT INTO profile_dropdown(profile_id,profile_source)
--VALUES (7,"Others");

--Insertion of statusTable
--INSERT INTO status_dropdown(status_id,select_status,select_status_comments)
--VALUES (1,"Selected","");
--INSERT INTO status_dropdown(status_id,select_status,select_status_comments)
--VALUES (2,"Rejected","");
--INSERT INTO status_dropdown(status_id,select_status,select_status_comments)
--VALUES (3,"Hold","");